### ISSUE TITLE
Pebble Time pairing icon is off-center

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#189]
![image](https://user-images.githubusercontent.com/507922/139523403-197d4faa-9ae3-4bc6-ad50-77c7c3cba1cc.png)

**Comment by hellcp** [comment]
This is because there is no size specified for https://github.com/pebble-dev/mobile-app/blob/master/lib/ui/setup/pair_page.dart#L124-L126, while it's constrained by the external container. The container on the outside is probably not needed, so the best solution would be to remove the container and set the size of the icon to 56.
